child_config: Tests/.swiftlint-tests.yml

disabled_rules:
  - line_length
  - file_length

opt_in_rules:
  - missing_docs

included:

excluded:
  .build

trailing_comma:
  mandatory_comma: true

vertical_whitespace:
  max_empty_lines: 2

identifier_name:
  excluded:
    - id
    - i
    - os
    - Step
    - Wait
    - Trigger
    - Group
    - Steps
    - Block
    - Input
    - Option
    - TextField
    - SelectField
    - Command
    - ArtifactPath
    - Env
    - Agent
    - RetryRule
    - Matrix
    - Dimension
    - Adjustment
    - GlobalEnv
    - DefaultAgent
    - Metadata
    - NotifyEmail
    - NotifySlack
    - NotifyWebhook
    - StepNotifySlack
    - StepNotifyGitHubCheck
    - StepNotifyGitHubCommitStatus
